### PR TITLE
Fix long get requests error

### PR DESCRIPTION
**Pull request by glebvk85**
If the SQL-request to the clickhouse is too large, the clickhouse server returns a 400 error for this HTTP request. Putting the SQL-request in the HTTP request body solves the problem.

### CODE REVIEW

**Comment by DoubleDi** [comment]
Hi! Please send some example queries.

**Comment by glebvk85** [comment]
> Hi! Please send some example queries.
> Not a long time ago we have added the sql query in the GET request query parameter for chproxy support. I am not sure we want to drop the support.
> The query should be in the url on select queries, and in the body for insert queries

Hi! We use very long queries (more than 20-30 thousand characters). You can test the error by simply making the query I added in the test:
`Select '{text over 10-20 thousand characters}'`

**Comment by DoubleDi** [comment]
Understandable when using large IN (...) queries. Consider making this option cofigurable.

**Comment by DoubleDi** [comment]
@glebvk85  please test the just merged solution with in body queries

**Comment by glebvk85** [comment]
> @glebvk85 please test the just merged solution with in body queries

Yes, it works, thanks. I close this PR.

**Pull request closed without merging**
