### PR TITLE
Support Array(Nullable(TypeName)) Parse() 

### PR DESCRIPTION
**Pull request by ElrondfromRussia**
I've noticed some time ago that Array(Nullable(TypeName)) elements can not be read from ClickHouse database properly.
So there's a solution for some data types.
P.S. + some tests of course
P.S.2. + fixed nil array element Parse() panic (dataparser.go:320)

dataparser.go: Array(Nullable(TypeName)) Parse() support where TypeName:
- UInt8-64
- Int8-64
- Float32-64
- String (also with escape seqs)
- Date (also with timezone)
- DateTime (also with timezone)
- Decimal
- Enum
- Uuid
- LowCardinality

### CODE REVIEW

**Comment by DoubleDi** [comment]
Hi @ElrondfromRussia!
Thanks for your contribution. 

Please correct the formatting (issues in CI) and add some NULL (\N) values in tests, to actually check, that your dataparser works fine with those cases.

Please also clearify what do you mean by "not sure about safety ^^".

**Comment by ElrondfromRussia** [comment]
Hi @DoubleDi!
Thanks for your answer!
Okay, done

**Comment by DoubleDi** [comment]
Thanks for the fast update @ElrondfromRussia 
Looks great. 

One last thing. Can you please add nullable items into Array(Nullable(T)) tests, so we see the correct parsing there.

Will be merging ASAP.

**Comment by ElrondfromRussia** [comment]
@DoubleDi, as far as I know, golang does not support nil values in typed slices.
So, to be honest, I have no idea how to test it in a correct way...

**Comment by DoubleDi** [comment]
Yes, that is correct, but how will it work, if clickhouse will return
[1, 2, NULL] ?
Will this get parsed correctly?

**Comment by ElrondfromRussia** [comment]
@DoubleDi, first way of parsing [1, 2, NULL] is reading only 1 and 2 (last commit contains this logic) 
For example, [1,2,NULL] -> [1,2], ['a','\N','b'] -> ['a,','b']

Second way is - to read default type values intead of NULL (reflect.Zero(reflect.TypeOf((*<data type should be here>)(nil)).Elem())).
For example, [1,2,NULL] -> [1,2,0x0], ['a', 'b', 'NULL'] -> ['a','b',''] and etc. for different data types

Not sure about what way is better

**Pull request merged**
