### PR TITLE
Add LazyQuotes for groupArray(String)

### PR DESCRIPTION
**Pull request by arkie**
String values that contained a `"` would cause the csv parser to choke (see updated test)

### CODE REVIEW

**Comment by arkie** [comment]
@bgaifullin in case initial PR was missed

**Comment by bgaifullin** [comment]
Please check that this PR is still actual.

**Comment by twalwyn** [comment]
This is still needed. We ran into this recently.

**Comment by arkie** [comment]
@bgaifullin merged, verified that the tests still fail with the same CSV issue without LazyQuotes.

**Comment by bgaifullin** [comment]
LGTM, thank you for PR

**Pull request merged**
