### PR TITLE
Added support for gzip compression of request body

### PR DESCRIPTION
**Pull request by Fiery-Fenix**
Useful for massive data load to ClickHouse using simple INSERT INTO
On test environment data flow was dropped from 400MBit to 65Mbit using this patch

### CODE REVIEW

**Comment by Fiery-Fenix** [comment]
Fixes #112

**Comment by Slach** [comment]
LGTM

**Comment by Slach** [comment]
@DoubleDi could we merge it and maybe make a new release?

**Comment by DoubleDi** [comment]
Great work @Fiery-Fenix.
Will do @Slach

**Pull request merged**
