### PR TITLE
skip only not string

### PR DESCRIPTION
**Pull request by glebvk85**
Sorry, I was wrong: we can leave only one value if it is of string type, otherwise it is a separator.

### CODE REVIEW

**Comment by DoubleDi** [comment]
Is this PR needed @glebvk85 ?

**Comment by glebvk85** [comment]
> Is this PR needed @glebvk85 ?

Yes, it is necessary, this is the correction of the mistake I made

**Comment by DoubleDi** [comment]
> Yes, it is necessary, this is the correction of the mistake I made
And what about the other types, like FixedString(N), LowCardinality(String), Nullable(String) - what will happen with them?

**Comment by glebvk85** [comment]
> > Yes, it is necessary, this is the correction of the mistake I made
> 
> And what about the other types, like FixedString(N), LowCardinality(String), Nullable(String) - what will happen with them?

Yes, you need to skip all types that do not convert to string

**Comment by DoubleDi** [comment]
All these types also use the string parser:
https://github.com/mailru/go-clickhouse/blob/master/dataparser.go#L553
And also we have Array(String), Tuple(String).
Are you sure we going the right way here?

**Comment by glebvk85** [comment]
Yes, when using the tsv format, we can never separate the empty string as part of the data from the empty delimiter string. I was hoping to do it with some heuristics, but this is the wrong way. Now it is better to skip the blank line, as it was in the previous version. To solve the problem, go to the format JSONCompactEachRow https://clickhouse.tech/docs/ru/interfaces/formats/#jsoncompacteachrowwithnamesandtypes

**Comment by DoubleDi** [comment]
TestTextRowsEmpty test failing

**Comment by DoubleDi** [comment]
When does an empty delimiter string occur in the result value?

**Comment by glebvk85** [comment]
> When does an empty delimiter string occur in the result value?

https://clickhouse.tech/docs/en/sql-reference/statements/select/group-by/#with-totals-modifier

In TabSeparated* formats, the row comes after the main result, preceded by an empty row (after the other data).

**Pull request merged**
